### ISSUE TITLE
glCreateBuffers - Runtime Exception Visual Studio 2017

### ISSUE THREAD

**Issue by Shot511** [Dav1dde/glad#103]
Hey,

Today I switched from GLEW to GLAD and encountered the following problem. When I call glCreateBuffers function from the code, in runtime Visual Studio tells me that there was an exception:

`Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.`

For the compiler everything is ok, and while I was using GLEW everything worked just fine. I've generated GLAD using webservice - here is a link: http://glad.dav1d.de/#profile=core&language=c&specification=gl&loader=on&api=gl%3D4.5&extensions=GL_ARB_debug_output

Have I missed something?

**Comment by Shimmen** [comment]
Are you compiling `glad.c` with the rest of your program or have you compiled it into a library beforehand?

**Comment by Shot511** [comment]
I've added it to the Visual Studio project (visible in Solution Explorer), so the answer is I'm compiling `glad.c` with the rest of my program.

**Comment by Shimmen** [comment]
Hm, that sounds odd to me. Is it only `glCreateBuffers` that cause the error and is it the first gl call in your program?

**Comment by Shot511** [comment]
I think that's the only one function that causes this error. When I commented this line of code (and all lines of code that corresponds to this function) everything works fine. And no, it's not the first (first I create GL context and then initialize GLAD) call in my program.

**Comment by Shimmen** [comment]
Hi again, sorry for my late reply, I totally forgot about this.

I'm not sure what the cause might be, but I assume it has something to do with the function not loading properly, also possibly in conjunction with the fact that it's a GL 4.5 function (since other GL functions work properly). @Dav1dde could probably provide more help.

**Comment by Dav1dde** [comment]
Hey,

I unfortunately haven't seen your problem before and I can't really give any help without research and code. The only thing which comes to mind is, you might sight the APIENTRY macro. The APIENTRY definition from windows.h is used by default (which is stdcall), if you don't set your own before including glad.

Check if you set APIENTRY somewhere or if you have APIENTRY set before including glad (e.g. `#ifdef APIENTRY #error`).

**Comment by Shot511** [comment]
Hey,

After investigating `glad.h`, I've found the following lines of code:

```
#ifndef APIENTRY
#define APIENTRY
#endif
#ifndef APIENTRYP
#define APIENTRYP APIENTRY *
#endif
```

In my `glad.h` (which should be the same for you) these code can be found on lines 38-43.

After changing it to the following code (just added `__stdcall` after `#define APIENTRY`):

```
#ifndef APIENTRY
#define APIENTRY __stdcall
#endif
#ifndef APIENTRYP
#define APIENTRYP APIENTRY *
#endif
```

Everything works fine, and no error occurs.

**Comment by Dav1dde** [comment]
Right above the code you showed:

```c
#if defined(_WIN32) && !defined(APIENTRY) && !defined(__CYGWIN__) && !defined(__SCITECH_SNAP__)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN 1
#endif
#include <windows.h>
#endif
```

[`windows.h` contains an `APIENTRY` definition, which is defined as `__stdcall`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx) but you must redefine it somewhere in a library you include or your own code before including glad, that's why glad doesn't pick it up. It seems you have a more serious problem in your codebase.

Nevertheless I am glad it works for you now.
