### ISSUE TITLE
Update CMake in glad2

### ISSUE THREAD

**Issue by Dav1dde** [Dav1dde/glad#110]

**Comment by madebr** [comment]
I have added a cmake module to the `glad2_cmake` of my fork [here](https://github.com/madebr/glad/tree/glad2_cmake).

Properties:
- able to bootstrap: adding a new `glad_add_library` will correctly regenerate the gl sources on the next build
- only regenerates the gl sources when some argument changes. A clean does not remove the gl sources (although there is an issue)
- the `args.txt` file is needed to be sure that the args for generated files are the same (because the `add_custom_command` comand is removed once the gl sources are generated, we have to manually do some bookkeeping)
- add custom `regenerate` target to give users the ability to force regeneration of the gl sources
- the glad script can be forced by passing `-DGLAD_BIN=$PATH_TO_GLAD` to cmake
- needs the `GLAD_MODULE_PATH` variable defined

Known issue(s):
- When issuing a clean directly after an initial build, without having initial glad sources present, will remove the glad sources. You have to do at least another make before the glad sources will not be removed by the 

I have also added travis ci to this branch: output https://travis-ci.org/madebr/glad/builds/414689829

**Comment by madebr** [comment]
I've modified my branch to incorporate your suggestions.
Changes:
- the `pip install` in travis is necessary to install the dependencies
- make use of your `python -m glad` approach: this can be overridden by setting the `PYTHONPATH` environment variable. (See the `.travis.yml` file)
- add a `CMakeLists.txt` in the `cmake` directory ==> `GLAD_MODULE_PATH` is not required anymore

**Comment by Dav1dde** [comment]
I played around with it a bit more: https://github.com/Dav1dde/glad/commit/963354674a4a0a9750b535aafe74cc3cd3648ca6

I made it so the `WORKING_DIRECTORY` gets set to the root path of the git repository (makes it so you don't have to modify `PYTHONPATH` anymore).

I was debating if I should embed the "real" commandline that was used into the comment within the header file, I decided against it mainly because of two reasons:

1) The web generator does not have a commandline
2) "all extensions" means all extensions available at the current point in time, so if Khronos releases a new extension this new extensions would also be included, which means a "re-generate with same options" yields a different result.

I think the current `args.txt` is fine, it is cmake related metadata, this also allows me to modify with header at one point without breaking cmake.

What do you think about my changes, anything else we should consider (apart from the failing tests in #166)?

**Comment by madebr** [comment]
I did not add `WORKING_DIRECTORY` because I wanted to decouple cmake and the glad repo.
This is still possible with your changes AND it works out of the box, so I am happy.

One thing I am not completely happy about, is that the variable `GLAD_CMAKE_DIR` is cached. This is done because it is needed in the `glad_add_library` function.
Maybe add `mark_as_advanced(GLAD_CMAKE_DIR)`?

NB: I've added a sleep to account for platforms where there is a clock skew between the filesystem time and the system time. I don't know whether 1 second is sufficient. This 1 second penaly only occurs on rebuilding the glad sources. Not on every build step.

I've added an extra commit to my [glad2-cmake branch](https://github.com/madebr/glad/tree/glad2-cmake).

**Comment by Dav1dde** [comment]
My CMake is very limited, I was under the assumption that the variable needs to be cached otherwise you cannot override it via commandline (is there more to it)?

I guess it makes sense to mark it as advanced, since overriding doesn't really make sense.

Your commit looks good, I guess that's all we need? If you have a small example laying around how one would include glad into a build that would be nice (just a hello world with CMake as build system).

**Comment by Dav1dde** [comment]
Also this is a valid concern: https://github.com/Dav1dde/glad/pull/160 - I can't test it right now but is this also a problem in the current branch?

If it's still a problem, I was considering adding an additional commandline argument `--all-extensions` or have `--extensions` accept a special value `--extensions=_all` to workaround this. (Not that important right now just something to keep in mind)

**Comment by madebr** [comment]
The current implementation assumes all extensions, unless `EXTENSIONS` with a list of extensions followingis is passed. If the list contains a `NONE` extension, it considers that zero extensions are required. This solution is not perfect but allows all possibilities:
- all extensions: no `EXTENSIONS` or empty `EXTENSIONS` list;
- no extensions: `EXTENSIONS NONE`; and
- some extensions: `EXTENSIONS EXT1 EXT2`

I've added a cmake file to all examples in the example c and c++ folders.
It seems these do not work.
- `gl_glfw` and `gl_sdl2` in the c folder work; and
- `hellowindow2` and `hellowindow2_macro` work in the c++ folder.

**Comment by Dav1dde** [comment]
Thanks a lot for your incredible help, I'll try to get this in by the end of this week (when I am back at home).
