### ISSUE TITLE
not clear what gladLoadGLLoader() returns

### ISSUE THREAD

**Issue by bkerin** [Dav1dde/glad#127]
The landing page shows this signature at one point:

     void gladLoadGLLoader(GLADloadproc);

But in my generated glad.h for 4.6 I find this:

     GLAPI int gladLoadGLLoader(GLADloadproc);

Looking in the implementation in glad.c I get the idea this fctn is supposed to return true on success, but it returns false for me, and yet things seem to work (I would sort of expect everything to fail if that fctn does).  So I'm not sure what's going on exactly, could be my error for sure.

**Comment by Dav1dde** [comment]
You're right, the function does return an integer (0 for failure).
```c
 void gladLoadGLLoader(GLADloadproc);
```

Usually glad only returns 0 when something went really wrong. The only thing I can think of why it still seems to work for you is because only the loading of extensions failed, but the core functions were loaded successfully.

Can you try stepping into glad to find out why it returns 0?

**Comment by bkerin** [comment]
Well coming back to this a week later I can't reproduce the behavior.  My best guess is I had a broken build as I had added some #ifdef USE_OPENGL_DEBUG_CONTEXT about then the on-ness of which the Makefile didn't capture as a build dependency.  The issue with the wrong signature for gladLoadGLLoader() on the landing page stands but otherwise I think this is a non-issue.
