### ISSUE TITLE
GLintptrARB & GLsizeiptrARB Throw Errors .

### ISSUE THREAD

**Issue by Zagool** [Dav1dde/glad#148]
Sorry this is my first time on reporting issues .
i Got 150 errors from glad.h , so i start looking around 
and i found GLintptrARB & GLsizeiptrARB Should Change to GLintptr & GLsizeiptr .
With this Change my error gone away . 
Tnx

**Comment by Dav1dde** [comment]
Thanks for the report. This was probably caused by an update by Khronos: 
https://github.com/KhronosGroup/OpenGL-Registry/commit/d1467468cdb3826a97b68845948979deb703e9b1#diff-b38552ce46ac15be44f6e96be71f6bef

That commit happened because of https://github.com/KhronosGroup/OpenGL-Registry/issues/162

I'll try to fix this immediately.
