### ISSUE TITLE
can not access khronos .xml spec due to robots.txt

### ISSUE THREAD

**Issue by filipwasil** [Dav1dde/glad#16]
python2 main.py --out-path=./ --generator=c does not work

it fails on downloading specs from khronos:
https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/gl.xml

looks like it is blocked by robots.txt

https://www.google.pl/?gws_rd=ssl#q=https:%2F%2Fcvs.khronos.org%2Fsvn%2Frepos%2Fogl%2Ftrunk%2Fdoc%2Fregistry%2Fpublic%2Fapi%2Fgl.xml

**Comment by Dav1dde** [comment]
This seems to be a problem with the khronos website (unrelated to glad's code). Downloadcode seems to work sporadically, also I have problems loading the API files and their main website in my browser as well.

Workaround: download the files manually and place them in the same directory as `main.py`, the local files will be used instead of downloading them. (You might need to download [khrplatform.h](https://www.khronos.org/registry/egl/api/KHR/khrplatform.h) and place it in `include/KHR/` (create the directory if it doesn't exist already).
