### ISSUE TITLE
Add support for vcpkg

### ISSUE THREAD

**Issue by hbobenicio** [Dav1dde/glad#189]
It would be awesome to have glad also available on vcpkg. :)

I know that conan is currently being supported but for projects already using vcpkg or planning to just use vcpkg, this could be a pain (to use more than one dependency management...).

**Comment by Dav1dde** [comment]
Conan support exists because of the amazing people over at @bincrafters - I am not the one maintaining the conan package(s). I am happy to link to 3rd party packages made by others but I currently don't have the time to create nor to maintain more packages.

If you want to add glad to [vcpkg](https://github.com/Microsoft/vcpkg) feel free to do so, but unfortunately I cannot support this right now.
