### ISSUE TITLE
Accessviolation when 2 projects use same glad lib

### ISSUE THREAD

**Issue by WhoseTheNerd** [Dav1dde/glad#195]
I have 2 projects that link glad. 1 project is DLL and other one is exe. Then glad throws Accessviolation error when trying to call OpenGL functions on exe project. On the DLL project it is fine. 
Any ideas?

**Comment by fluffrabbit** [comment]
Just a random guess here. Runtime loading of dynamic libraries (which Glad does for extension loading, but it's a little complicated) requires OS-specific functionality in the form of another dynamic library (compile-time dependency). On POSIX it's libdl, and Windows has its equivalent. 

My guess is you didn't link your EXE with the necessary loader/dylib thingy, or you're using something like SDL/SFML/GLFW and you didn't set up the Glad loader handling code for that correctly. It's a little esoteric, and depends on which library you're using, but if it weren't a problem Glad wouldn't exist in the first place.

I hope that helps!

**Comment by WhoseTheNerd** [comment]
So I need to use gladLoadopengl thing on executable too? Thats done in the dll project.

**Comment by WhoseTheNerd** [comment]
For info. It didn't work.

**Comment by fluffrabbit** [comment]
Absent further information it's hard to diagnose the problem. You need:

* gladLoad* to be called once (and correctly) when you initialize the window, making sure it references either an SDL-like library or is configured to roll its own dough with the system DLL/dylib loader (your mileage may vary) ((see below))
* your EXE compile-time linked with either a GL initializer (such as SDL if you use it) OR your system's dynamic library loader (such as libdl on Linux/Mac)

Other than those two things, I couldn't venture a guess. It could be a Windows-specific thing, but more likely it's a bug in your code.

**Comment by WhoseTheNerd** [comment]
Could you say what do you need to diagnose the problem? Source Code? Code that initializes glad?

**Comment by WhoseTheNerd** [comment]
My solution is to make glad loader give back glad context or something and then in my exe file I can use glad loader with context generated from dll file. I have no idea if that is practical.

**Comment by fluffrabbit** [comment]
Interesting. AFAIK there is no such thing as a Glad context. Glad gives you a GL context. OpenGL is a state machine. You call glThis and glThat, which modify the global state of what OpenGL calls "server" memory, which is a part of your graphics memory devoted to your GL context, usually one per program. (CPU or GPU; depends on your drivers.) WebGL objectifies it, but that's a high-level wrapper and not raw OpenGL. Glad is raw OpenGL.

I stopped using Windows around the time I started learning C++, so I'm not sure if it works the same way, but on POSIX systems dynamic libraries share a good chunk of address space with your main source file. Everything is basically an "object file", so a DLL should be no different from another .c/.cpp file compiled alongside your main .c/.cpp file and statically linked. No difference. But memory addresses and pointers are a pain in the ass, so if you've got a bug it will be hard to catch.

What works for me is putting all my GL stuff in a header file included from my main source file. I use separate objects for large chunks of code that save compilation time by being compiled in advance, such as other people's libraries. For my own code, especially GL stuff, I keep it as close to my main function as possible, because GL is where most of the bugs come from, directly or indirectly.

I would not advise passing a pointer to your GL context from a DLL. High-level graphics libraries such as OGRE wrap all the GL stuff in wrapper functions, so (having not used ogre) instead of calling glBufferData you would call something like updateMesh, which abstracts away the low-level OpenGL nitty-gritty, and all of said GL nitty-gritty stays in one place like a maximum security cell block. I find that to be saner.

**Comment by WhoseTheNerd** [comment]
For development purposes I need to have access to OpenGL on both projects. I might go to back to GLEW, because it supports that. GLEW can be initialized in one project and other project already have access to OpenGL functions. Glad just throws access violation exception on OpenGL functions, function ptr was 0x00.

**Comment by WhoseTheNerd** [comment]
Here's the access violation image: http://prntscr.com/m98m2c
Heres Source code: https://www.dropbox.com/s/de7ym5iqyiukdw1/Sparky.zip?dl=0

I linked my dll and exe with glfw and glad. Then dll initializes glfw and glad. Then exe tries to load glad. That fails at compile time, because glfwProcAddress is  not defined, I include GLFW to my project, then I get linker error. I link my glfw to my project, then I get glfw error: glfw is not initialized. Then I initialize glfw. Getting same error message, then I removed glad load function call, Then I get glfw error: Win32: Failed to register window class: Class already exists. I don't know what to do now.

**Comment by Dav1dde** [comment]
Think of it as if you had two completely separate programs running. Program A has a completely initialized OpenGL context (including glfw and glad) the other (program B) does not. Calling OpenGL functions in program A will work, doing so in program B will give you the access violation because there is no context. 

Now you don't want to make a second OpenGL context in program B, but you want to re-use the OpenGL context from program A, so you don't want to re-initialize glfw and make a new window+context, but you need a way to access the context of program A in program B.

How can you do this? E.g. expose `glfwGetProcAddress` from program A to program B, you could make a simple wrapper function which does the same, or just a global where you store the function pointer to `glfwGetProcAddress` then retrieve that function/global in program B and pass it to glad.


PS:
The reason why you cannot use glfw functions in program B is the same reason why you cannot use OpenGL functions in program B, the global state required to use the functions is simply not available in program B only in program A.

**Comment by WhoseTheNerd** [comment]
Thank You, It worked! I made method wrapper for glfwGetProcAddress and used it in initialization for DLL and Sandbox.

**Comment by Dav1dde** [comment]
Awesome!

**Comment by liamdx** [comment]
> Thank You, It worked! I made method wrapper for glfwGetProcAddress and used it in initialization for DLL and Exe projects.

Can you clarify what you mean by this? I'm experiencing the same access violation but don't know how to create a shared context.

**Comment by Dav1dde** [comment]
@liamdx you don't have to create a shared context, the context is already global (somewhat). You just need to make it available, one option to make it available is something like this:

Library dynamically loaded:
```c
void libInit() {
    // create window/opengl context etc.
}

void* libGetProcAddress(const char *name) {
    return (void*) glfwGetProcAddress(name);
}
```

Binary dynamically loading/linking with library:
```c
void main(void) {
    libInit();

    gladLoadGLLoader(libGetProcAddress);
}
```


But there are other ways as well:
* make glad a dynamic library and dynamically link with it in lib and your program
* re-use the glad symbols from the lib (I haven't tried it, but in theory it should work if you set `GLAD_GLAPI_EXPORT` when compiling your library dll)

**Comment by liamdx** [comment]
> @liamdx you don't have to create a shared context, the context is already global (somewhat). You just need to make it available, one option to make it available is something like this:
> 
> Library dynamically loaded:
> 
> ```c
> void libInit() {
>     // create window/opengl context etc.
> }
> 
> void* libGetProcAddress(const char *name) {
>     return (void*) glfwGetProcAddress(name);
> }
> ```
> 
> Binary dynamically loading/linking with library:
> 
> ```c
> void main(void) {
>     libInit();
> 
>     gladLoadGLLoader(libGetProcAddress);
> }
> ```
> 
> But there are other ways as well:
> 
> * make glad a dynamic library and dynamically link with it in lib and your program
> * re-use the glad symbols from the lib (I haven't tried it, but in theory it should work if you set `GLAD_GLAPI_EXPORT` when compiling your library dll)

Apologies for delay I did not expect a 2 year old post to be replied to so quickly! Thanks for taking the time to reply, I think I will just build GLAD as a DLL, I want to reuse it in a few plugins which will be added in to a client exe so dll seems like the most sensible option. Thanks again for taking the time to reply, it's really appreciated :)

**Comment by Nixzon** [comment]
Guys,I'm having the same error, I've been struggling with that for a month. Could you state what fixes it
