### ISSUE TITLE
How do I initialize EGL Glad headless?

### ISSUE THREAD

**Issue by half-potato** [Dav1dde/glad#205]
Without a display attached, I obviously get NULL when running XOpenDisplay. However, running that command I get NULL when I run gladLoaderLoadEGL for the version. How do I circumvent this issue? Sorry for the lack of details, I don't really know what kind of information to provide.

**Comment by half-potato** [comment]
So I managed to create a virtual display and the application can find it, but it still fails to load EGL. I suspect it has something to do with having multiple GPUs.

**Comment by Dav1dde** [comment]
I am not sure if I can help you here.

in the glad2 branch I have an example: https://github.com/Dav1dde/glad/blob/glad2/example/c/egl_x11/egl_x11.c

Also the EGL loader has been improved (but it probably won't fix your problem).

**Comment by half-potato** [comment]
I found that commenting out the line that returns 0 when the display is NULL in the function find_coreEGL fixes this issue. I couldn't find the line in the repo I imagine it's generated.

**Comment by half-potato** [comment]
`diff --git a/gibson/core/channels/glad/egl.c b/gibson/core/channels/glad/egl.c
index 57c1181..d7a779e 100644
--- a/gibson/core/channels/glad/egl.c
+++ b/gibson/core/channels/glad/egl.c
@@ -236,9 +236,10 @@ static int find_coreEGL(EGLDisplay display) {
     if (display == EGL_NO_DISPLAY) {
         display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
     }
+    /*
     if (display == EGL_NO_DISPLAY) {
         return 0;
-    }
+    }*/
 
     version = eglQueryString(display, EGL_VERSION);
     (void) eglGetError();
`

**Comment by teburt** [comment]
I think you'd want to use eglGetPlatformDisplay instead of eglGetDisplay (the latter implementation probably assumes it's not offscreen)

There's some info that may be relevant here: https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/

**Comment by Dav1dde** [comment]
I assume this is done, feel free to re-open if you have something else to add/ask.

**Comment by chloekek** [comment]
The Nvidia blog post linked above was indeed very helpful. However, I did still stumble into a few issues. In case anyone else finds this issue, here are my findings:

In the Nvidia blog post, I needed the approach under “EGL with multiple GPUs”, not the one under “Creating an OpenGL context”. This is because `eglGetDisplay(EGL_DEFAULT_DISPLAY)` fails if the `DISPLAY` environment variable is unset, as it is in a headless setup. (Perhaps this is because I use Mesa, and Nvidia’s driver might behave differently.)

Another issue I ran into was that `gladLoadEGL` takes an `EGLDevice`, but creating an `EGLDevice` requires calling EGL functions, which are shadowed by macro definitions in `glad/egl.h`. To work around this, I used the following code:

```cpp
#include <glad/egl.h>

#undef eglGetPlatformDisplay
#undef eglGetProcAddress
#undef eglInitialize

extern "C"
{
    EGLDisplay eglGetPlatformDisplay(EGLenum, void*, EGLAttrib const*);
    void (* eglGetProcAddress(char const*))();
    EGLBoolean eglInitialize(EGLDisplay, EGLint*, EGLint*);
}
```

Then, to obtain `eglQueryDevicesEXT`, call `eglGetProcAddress` manually:

```cpp
#undef eglQueryDevicesEXT

auto eglQueryDevicesEXT =
    reinterpret_cast<PFNEGLQUERYDEVICESEXTPROC>(
        eglGetProcAddress("eglQueryDevicesEXT")
    );
```

After calling `eglQueryDevicesEXT`, `eglGetPlatformDisplay`, and `eglInitialize`, as layed out under the “EGL with multiple GPUs” section in the Nvidia blog post, you can call `gladLoadEGL(display, eglGetProcAddress)` and hopefully it will return 10004 or 10005. Now you can call the remaining EGL functions.

In my case `eglChooseConfig` also didn’t come up with any configs, which is fine since I can just use `EGL_KHR_no_config_context` and `EGL_KHR_surfaceless_context`.

**Comment by Dav1dde** [comment]
@chloekek you can just pass `NULL` as a device and re-load the symbols once you have a specific non-default device
