### ISSUE TITLE
Use namespaces for more modern code

### ISSUE THREAD

**Issue by kennycastro007** [Dav1dde/glad#219]
The entire codebase using the "glad" prefix on all its functions. I was thinking that maybe it should switch to using namespaces but I realize that would be a breaking change so maybe it could be set with a compile definition like `#define GLAD_USE_NAMESPACES` or something like that so that it's an optional feature?

**Comment by fluffrabbit** [comment]
It would have to be a generator flag rather than a define. I'm not aware of a metaprogramming technique in C/C++ that changes the names of functions, and duplicating the declarations in one file would make for a lot of bloat.

**Comment by kennycastro007** [comment]
The files are generated rather than statically typed it seems, since I couldn't find the source files in the repo, but how about having 2 includes? Set the flag and it includes the namespace version rather than the prefix version? That wouldn't break anything as the default would be prefix but those who want to use namespace could set the flag and get them

**Comment by Dav1dde** [comment]
You can for now easily do this using `sed` or any search-replace tool, just use it on the generated code.

This is also discussed in: https://github.com/Dav1dde/glad/issues/198 - I plan to add this to glad2 as an option at one point (PR welcome), but this isnt exactly high priority for me (since it is pretty easy to do with sed)
