### ISSUE TITLE
glGetString causes null exception

### ISSUE THREAD

**Issue by MythreyaK** [Dav1dde/glad#238]
This code, with glad causes a null exception, as in `glad.c`, the function id defined as `NULL`. 

```c
#include <glad/glad.h>
#include <GLFW/glfw3.h>

int main(void) {
    GLFWwindow* window;

    /* Initialize the library */
    if (!glfwInit())
        return -1;
    
    /* Create a windowed mode window and its OpenGL context */
    window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
    if (!window) {
        glfwTerminate();
        return -1;
    }

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    /* Loop until the user closes the window */
    while (!glfwWindowShouldClose(window)) {
        /* Render here */
        glClear(GL_COLOR_BUFFER_BIT);
        printf("%s\n", glGetString(GL_VERSION));

        /* Swap front and back buffers */
        glfwSwapBuffers(window);

        /* Poll for and process events */
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}
```
Instead of glad, when I include the platform headers `<gl/gl.h>` it works fine. 

I am sure I am missing something, but am not sure as to what it is. Help would be appreciated, thanks!

**Comment by MythreyaK** [comment]
Huh.. I was able to fix the issue by digging around the source files. I called `gladLoadGL();` before calling any other functions. Is that the right way to do it?

**Comment by Dav1dde** [comment]
Yeah that's exactly what you need to do, after making your context current `glfwMakeContextCurrent` you need to initialize glad. You can do this via `gladLoadGL` or since you're using GLFW you should make use of GLFW and initialize glad using `gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)` instead. Also for safety you check the return value of the loader function.

You can compare your code to [this example](https://github.com/Dav1dde/glad/blob/master/example/c%2B%2B/hellowindow2.cpp).

Your code:

```c
    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    /* Load OpenGL functions using glad */
    if (!gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)) {
        glfwTerminate();
        return -1;
    }
```

**Comment by MythreyaK** [comment]
Ahh Thank you very much! 
Also, I noticed this is tagged as `glad1`, where do I get `glad2`?

**Comment by MythreyaK** [comment]
Also, are `<glad/gl.h>` and `<glad/glad.h>` the same? I've seen examples with the first one floating around.

**Comment by MythreyaK** [comment]
I've been following tutorials, but can't seem to be able to use `glGenLists`, `glFrustum`, `glVertex3f` functions. How do I load these? GLFW examples seem to just import `<glad/gl.h>` where these are defined. I can't seem to get these definitions from the web generator. What am I missing?

**Comment by Dav1dde** [comment]
These are "deprecated" OpenGL < 3(.3) functions and really really old tutorials, you generally don't want to follow such a tutorial.

If you really want these functions you have to select the compatibility profile and at least OpenGL 2.1. But again I don't recommend doing this, if you see a tutorial with `glVertex3f` or `glBegin`/`glEnd`, look for another one.

GLFW is currently updating their examples for glad2 (which you can find at https://glad.sh or in the glad2 branch), it has a reworked API and more features. It's fine to use, but I am still not certain about a few things (e.g. I might rename files/functions), that's why I haven't put it on master here or released a "non-beta" version yet.

**Comment by MythreyaK** [comment]
Oh I didn't know that. Thanks for letting me know! 

I've just begun learning about OpenGL and Vulkan. Is [learnopengl.com](https://learnopengl.com) a good enough resource? If not, I could really use some suggestions. I plan to use at least OpenGL 4.2, since it seems widely supported. 

I have another question, if I might add. I've seen a lot of people saying OpenGL is loosing it's utility. How true is this? I'm learning OpenGL to familiarize myself with rendering and add it to my skillset. Will this improve my employability, if at all?

**Comment by Dav1dde** [comment]
> I've just begun learning about OpenGL and Vulkan. Is [learnopengl.com](https://learnopengl.com) a good enough resource? If not, I could really use some suggestions. I plan to use at least OpenGL 4.2, since it seems widely supported.

It's a really good resource.

> I have another question, if I might add. I've seen a lot of people saying OpenGL is loosing it's utility. How true is this? I'm learning OpenGL to familiarize myself with rendering and add it to my skillset. Are employers looking for this skill?

I personally doubt OpenGL is going to leave soon, even if it goes the skills you learn are useful with any other API, DirextX, Vulkan or anything else. You're not just learning to use an API, but the math and concepts behind it.

Generally if you have questions like this, there are some amazing people on Freenode #OpenGL, which are a lot more qualified to answer these questions.

**Comment by MythreyaK** [comment]
Thank you very much for the resources, and patiently helping me find my way!
