### ISSUE TITLE
Nim enum issue

### ISSUE THREAD

**Issue by Develon5543** [Dav1dde/glad#257]
Hello! I just recently picked up Nim and wanted to use glad for opengl bindings. When I import the gl.nim file though, I get this error. (Generated OpenGL 3.3 Core with "Generate a loader" checked.)

`gl.nim(107, 39) Error: -1 can't be converted to uint64`

I peeked at the code, and it's in the section dealing with opengl enums.

**Comment by fluffrabbit** [comment]
In C, -1 as a 64-bit unsigned int is equal to the maximum value of a 
64-bit unsigned int (it wraps around). That doesn't solve the problem, 
but I hope it gives it some context.

**Comment by Dav1dde** [comment]
@johnnovak ping

**Comment by johnnovak** [comment]
Thanks @Dav1dde 

@Develon5543 Can you please give me some details? Which Nim version are you using, is it the latest 1.0.6? Can you give me the exact parameters you used for generating the GL file?

**Comment by Develon5543** [comment]
@johnnovak  Yes, I'm currently using Nim 1.0.6. To generate the GL file, I went to [the website](https://glad.dav1d.de/) and selected the language Nim. I kept the specification as OpenGL, set the gl api to 3.3, and picked the Core profile. I kept the other apis set to None, and didn't enable any extensions. The only option I checked was "Generate a loader". That gave me a zip file that only contains gl.nim which is what I was having issues with.

**Comment by johnnovak** [comment]
Thanks, I'll have a look today or tomorrow. I remember I had this issue before but I thought I fixed it. Anyway, I'll fix it better if it's still an issue :)

**Comment by johnnovak** [comment]
Ok, it turns out my memory is not so bad and I did fix this a while ago:

https://github.com/Dav1dde/glad/commit/9c248094b5b9f231e737e14d88cbbb7e3937d46#diff-c52e84971d5983683d03074508272340R525-R528

The problem is that the webservice is running a version earlier than this commit.  This has been confirmed by comparing the output of the webservice with the output of the current master version running locally.

Solution: @Dav1dde please update the webservice to use the latest master version.

In the meantime, you can clone the repo, check out the master branch and run the following command locally to get what you need:

```
python -m glad --extensions , --spec gl --api gl=3.3 --profile core --generator nim --out-path out
```

Alternatively, you can just change the following two `const` values manually to this:

```nim
  GL_TIMEOUT_IGNORED*: uint64 = 0xFFFFFFFFFFFFFFFF'u64
  GL_TIMEOUT_IGNORED_APPLE*: uint64 = 0xFFFFFFFFFFFFFFFF'u64
```

**Comment by Develon5543** [comment]
Thank you so much, @johnnovak! I'll manually edit the files this time. Thank you for your help.

**Comment by Dav1dde** [comment]
I updated it just now:

![image](https://user-images.githubusercontent.com/255721/77523109-8b993200-6e85-11ea-830a-bfbf22cfaf9f.png)

Sorry about that, I must have previously updated glad2 instead of glad on accident.

Thanks for looking into it @johnnovak
