### ISSUE TITLE
glad.h conflicts with macOS OpenGL headers

### ISSUE THREAD

**Issue by tellowkrinkle** [Dav1dde/glad#258]
It seems glad defines `__gl_h_` to prevent the main gl header from doing anything, but including `glext.h` causes lots of errors like `redefinition of 'glad_glClampColorARB' as different kind of symbol` as the define in `glad.h` messes up the function definition in `glext.h`

(Note: this only happens if you're compiling without `-fmodules`, as otherwise the gl headers stay unaffected by outside defines)

The headers included in the macOS OpenGL SDK: [MacGLHeaders.zip](https://github.com/Dav1dde/glad/files/4384226/MacGLHeaders.zip)

To reproduce: 
- Save the following in `test.c`:
```c
#include <glad/glad.h>
#include <OpenGL/gl.h>
#include <OpenGL/glext.h>
int main() { return 0; }
```
- Compile with `clang -Iglad/include test.c`

Expected result: Compiles with no errors

Actual result: Lots of errors

Full error example:
```text
In file included from test.c:3:
/System/Library/Frameworks/OpenGL.framework/Headers/glext.h:2152:13: error: redefinition of 'glad_glClampColorARB' as different kind of symbol
extern void glClampColorARB(GLenum target, GLenum clamp);
            ^
include/glad/glad.h:8796:25: note: expanded from macro 'glClampColorARB'
#define glClampColorARB glad_glClampColorARB
                        ^
include/glad/glad.h:8795:30: note: previous definition is here
GLAPI PFNGLCLAMPCOLORARBPROC glad_glClampColorARB;
                             ^
```

**Comment by Dav1dde** [comment]
This handling isn't perfect but not a bug, it is expected to have conflicting symbols since glad completely takes over OpenGL symbol definitions.

When using glad you should never include any of the system OpenGL headers. The `__gl_h` guard mainly exists to inform the user that he has included another gl provider before including glad.

That being sad, maybe glad should also define `__gl3_h`, `__glext_h_` and `__gl3ext_h_`. Or the completely opposite approach, not define the symbols at all.

**Comment by Dav1dde** [comment]
Added the guards to glad2, not going to add them to glad1.
