### ISSUE TITLE
unresolved external symbol _gladLoadGL

### ISSUE THREAD

**Issue by duzenko** [Dav1dde/glad#279]
I can't get a particular glad version working (v2, gl1.1, header only)

The sample project attached

[GLTest11.zip](https://github.com/Dav1dde/glad/files/4782459/GLTest11.zip)

![image](https://user-images.githubusercontent.com/1481807/84697259-80bade80-af56-11ea-8e82-08f4f1372c22.png)

**Comment by Dav1dde** [comment]
You have `ON_DEMAND` loading enabled, when on demand is enabled there is no `gladLoad*` function anymore and you have to set the loader via `gladSetGLOnDemandLoader`.

I am seeing `gladLoadGL` defined in the header, this is a generation bug, it should not exist, that's why you get the error at link time not compilation.

**Comment by duzenko** [comment]
OK, so this is a generation bug indeed then

**Comment by Dav1dde** [comment]
There is a reason it is marked experimental ;).

I'll fix it when I get around to it

**Comment by Dav1dde** [comment]
Should be fixed.
