### ISSUE TITLE
XCloseDisplay segfaults after gladLoadGLX

### ISSUE THREAD

**Issue by surafel911** [Dav1dde/glad#310]
I'm writing a small platform library for myself and updated my GLAD instance. I noticed the API changed and didn't include `gladLoaderUnloadGLX` anymore. Now the program segfaults after `XCloseDisplay` is called. `XOpenDisplay` works fine and is the only other external library called. I wondered why that is and realized that `libGL` is closed right after it's opened to load the GLX symbols:

```
int gladLoadGLX(Display *dpy, int screen) {
     int status = 0;
 
     if(open_gl()) {
         status = gladLoadGLXLoader((GLADloadproc)get_proc, dpy, screen);
         close_gl();
     }
 
     return status;
 }
```

Commenting out `close_gl` causes the program to run fine after reading [this](https://discourse.glfw.org/t/weird-segfault-in-xclosedisplay-called-from-glfwterminate/703/3l). Is the removal of `gladLoaderUnloadGLX` intentional or is the webservice bugging out?

**Comment by Dav1dde** [comment]
This is unfortunately an old bug, for WGL, GLX etc. I recommend you to look at [glad2](https://glad.sh), it handles this correctly.

**Comment by surafel911** [comment]
It was a link to the GLFW forum saying that removing a call to `_glfw_dlcose` when loading GLX solves the issue, and I figured that's what caused the issue in glad after looking at the source.

I will use glad2, but I just checked the webservice results for GL and the same problem exists there as well. glad2 doesn't have a GL loader generator yet.

**Comment by Dav1dde** [comment]
> I will use glad2, but I just checked the webservice results for GL and the same problem exists there as well. glad2 doesn't have a GL loader generator yet.

I am not sure what you mean by this.

The loading mechanism of glad2 is different and provides an unload function for GLX. It does not for GL because it is not required for GL.

OpenGL function pointers are not acquired from the .dll/.so, they are coming from the driver, the only thing required from the .dll/.so is the loading function, after loading is done, the library can be unloaded safely.

However this is different for GLX where function pointers are actually acquired from the .dll/.so, so it cannot be unloaded. Glad1 makes the mistake here of reusing the loading/unloading code of GL, glad2 provides a separate unload function ([as seen here](https://github.com/Dav1dde/glad/blob/glad2/example/c/glx_modern.c#L116)).

Also the website has a loader generator for all APIs.
