### ISSUE TITLE
[BUG] CMake Support on glad2

### ISSUE THREAD

**Issue by WildRackoon** [Dav1dde/glad#319]
There are several issues with the glad2 cmake target:

- If `KEEP_SOURCES` if not set, do not expect the library to be linkable (with CMake `target_link_libraries`), as `gl.h` within `GLAD_DIR` would be deleted.
Actually, I dont see why glad sources should ever need to be deleted after generation at all ? (same for args.txt) its already cleaned when regeneration is needed.

- Building a SHARED glad2 lib does not work : 
`GLAD_API_CALL_EXPORT_BUILD` needs to be defined with `target_compile_definitions("${TARGET}" PUBLIC GLAD_API_CALL_EXPORT)` if `BUILD_SHARED_LIBS` is `ON`
Adding CMake's native handling of shared libs with `#if defined(GLAD_API_CALL_EXPORT_BUILD) || defined(glad_EXPORTS)` works great. So it would require some tweaking with `configure_file()` to keep the nice multi-glad/custom naming to insert ${TARGET} instead of my 'glad'.

- I understand the concern with `regenerate_${TARGET}`, but the `sleep and touch CMakeLists.txt` part is really sketchy and not proper cmake use: CMake will rerun the custom_command/custom_target it the `COMMAND` changes, so you just need to change the arguments and everything is fine (See https://gitlab.kitware.com/cmake/cmake/-/issues/20828).

- Glad sources should not be in the `CMAKE_BINARY_DIR`, but rather in glad2's `PROJECT_BINARY_DIR`
- args.txt could be configured into the code, and we could then define a `std::string glad_getConfigString()` ot retrieve it programmatically.
- The WriteFile.cmake is not necessary since it should be done at config time, no need to do it post-build
- Why isn't the `CMakeLists.txt` in the root of the repo ?

How is glad2 coming up so far ? If it is not in a stale state, I would be happy to give a try to rework the `CMakeLists.txt` if you want ?

#320

**Comment by Dav1dde** [comment]
My cmake knowledge is very limited, the cmake setup itself has been contributed by others, for glad1 as well as glad2. All I do is try to keep it compatible and (somewhat) working.

I am thankful for every contribution that improves the cmake setup, as long as it remains compatible or there is a good reason for breaking something.

* Personally I am a fan of the glad2 setup using `glad_add_library`.
* `glad_getConfigString`: I don't want this in the API, I don't mind including it in an easily parseable comment though.
* root directory vs `cmake`: my personal preference, I want to keep the root scope as clean as possible, especially if cmake requires multiple files.

I have also considered removing the cmake files for glad2, simply because I can't (and don't want to) fully maintain and take care of them. Is there a good option to give control over the cmake setup to someone else (e.g. separately maintained packaging like `vcpkg`)?

**Comment by WildRackoon** [comment]
> I am thankful for every contribution that improves the cmake setup, as long as it remains compatible or there is a good reason for breaking something.
I would be happy to maintain the CMake setup 

> * Personally I am a fan of the glad2 setup using `glad_add_library`.
Yes I love it too, first reason to switch to glad for me was testing different contexts on an application and be able to switch seemlessly between configured glad builds from the website

> * `glad_getConfigString`: I don't want this in the API, I don't mind including it in an easily parseable comment though.
As you wish, that just a wild suggestion, but I understand glad ought to be minimalist

> * root directory vs `cmake`: my personal preference, I want to keep the root scope as clean as possible, especially if cmake requires multiple files.
It would require only a single `CMakeLists.txt`, It is not that unorthodox if you prefer to keep there though

> I have also considered removing the cmake files for glad2, simply because I can't (and don't want to) fully maintain and take care of them. Is there a good option to give control over the cmake setup to someone else (e.g. separately maintained packaging like `vcpkg`)?
Well, in the C++ world people generally frown upon package managers for a variety of reasons.  Not much people use vcpkg, and in my experience, is also a lot of additional work to get going that raw CMake/Bazel/Meson

**Comment by Dav1dde** [comment]
If the cmake directory does not have any major drawbacks other than changing a path, I would like to keep it there.

If you want to work on this, feel free to open a PR!

**Comment by Dav1dde** [comment]
Thanks! Tested and merged the PR.

I'll think about moving the cmake files back into the root directory.

**Comment by beeryt** [comment]
Having the `CMakeLists.txt` outside of the root directory does not play nice with CMake's `FetchContent`.
```
FetchContent_Declare(
  glad2
  GIT_REPOSITORY https://github.com/Dav1dde/glad
  GIT_TAG glad2
)
FetchContent_MakeAvailable(glad2)

glad_add_library(...)
```
This will fail because `glad_add_library` is undefined since the `CMakeLists.txt` is not in the root folder.

With a newer CMake 3.18 there is a `SOURCE_SUBDIR` option which can specify a subdirectory where `CMakeLists.txt` can be found, but it may be preferred to support more CMake versions by moving the `CMakeLists.txt` to the root directory.

**Comment by WildRackoon** [comment]
@beeryt You are right, I respect the decision to not promote it, but you should run the latest versions of CMake anyway imo.
