### ISSUE TITLE
406 Not acceptable on OS X

### ISSUE THREAD

**Issue by trevex** [Dav1dde/glad#32]
I am not sure why exactly but every simple request on OS X from `urlopen` and `urlretrieve` results in 406 errors.

OS X 10.10.4
Python 2.7.6

After some fiddling I realised, that it's related to missing the `User-Agent` header bit or the accepted mime type stuff. I quickly fixed it by overwriting the global opener instance with one using a sensible `User-Agent` value.

The commit can be found here: https://github.com/trevex/glad/commit/e5815d1b950b0c242e052624c94b6b5c4498b2bb

I'll test it later on my desktop pc running Ubuntu to check whether it breaks anything. I am not an experienced python developer, so let me know if I should send a pull request or you'll fix this in a more idiomatic or cleaner way...

**Comment by Dav1dde** [comment]
Thanks for figuring that out .. I can't since all my available IPs seem to be banned from Khronos for some reason.

I think the sanest version would be to attach an opener object to the [generator base class](https://github.com/Dav1dde/glad/blob/master/glad/lang/common/generator.py#L8) and an urllib2 opener to the spec class (with sane defaults if None was passed). 
The problem is, I have glad written in a way that it works with Python 2 and Python 3, I don't want to break the compatability.

So making a helper functions which sets up the right headers and calling it from `main()` is the right solution for now.

If you want to make a pull request, go for it! Otherwise I will fix this relativly soon. (If you need to generate a header you can use http://glad.dav1d.de as a workaround).

**Comment by Dav1dde** [comment]
Just a small followup, the Opener is not needed anymore, I messaged the khronos webmaster and these restrictions have been removed.
