### ISSUE TITLE
glad_vk_load_VK_KHR_swapchain bug.

### ISSUE THREAD

**Issue by sdragonx** [Dav1dde/glad#352]
```
static void glad_vk_load_VK_KHR_swapchain( GLADuserptrloadfunc load, void* userptr) {
    //if(!GLAD_VK_KHR_swapchain) return;
    if(!GLAD_VK_KHR_swapchain && !GLAD_VK_EXT_swapchain_colorspace) return;
    glad_vkAcquireNextImage2KHR = (PFN_vkAcquireNextImage2KHR) load(userptr, "vkAcquireNextImage2KHR");
    glad_vkAcquireNextImageKHR = (PFN_vkAcquireNextImageKHR) load(userptr, "vkAcquireNextImageKHR");
    glad_vkCreateSwapchainKHR = (PFN_vkCreateSwapchainKHR) load(userptr, "vkCreateSwapchainKHR");
    glad_vkDestroySwapchainKHR = (PFN_vkDestroySwapchainKHR) load(userptr, "vkDestroySwapchainKHR");
    glad_vkGetDeviceGroupPresentCapabilitiesKHR = (PFN_vkGetDeviceGroupPresentCapabilitiesKHR) load(userptr, "vkGetDeviceGroupPresentCapabilitiesKHR");
    glad_vkGetDeviceGroupSurfacePresentModesKHR = (PFN_vkGetDeviceGroupSurfacePresentModesKHR) load(userptr, "vkGetDeviceGroupSurfacePresentModesKHR");
    glad_vkGetPhysicalDevicePresentRectanglesKHR = (PFN_vkGetPhysicalDevicePresentRectanglesKHR) load(userptr, "vkGetPhysicalDevicePresentRectanglesKHR");
    glad_vkGetSwapchainImagesKHR = (PFN_vkGetSwapchainImagesKHR) load(userptr, "vkGetSwapchainImagesKHR");
    glad_vkQueuePresentKHR = (PFN_vkQueuePresentKHR) load(userptr, "vkQueuePresentKHR");
}

```
GLAD_VK_KHR_swapchain == 0 && GLAD_VK_EXT_swapchain_colorspace == 1.

os: win10.

**Comment by sdragonx** [comment]
A VK program compiled by my notebook. The graphics card does not support the "glad_vk_khr_swapchain" extension, but supports the "glad_vk_ext_swapchain_colorspace" extension. The code generated by glad only checks the first extension. If it is not supported, it returns, resulting in function loading failure.
**//if(!GLAD_VK_KHR_swapchain) return;**
**if(!GLAD_VK_KHR_swapchain && !GLAD_VK_EXT_swapchain_colorspace) return;// Modified**

**Comment by code-disaster** [comment]
I just tripped over the same issue.

GLAD sources generated via web interface, Vulkan 1.2, with all extensions added.

My Vulkan driver doesn't report VK_KHR_swapchain, so it skips `glad_vk_load_VK_KHR_swapchain()`, then crashes when trying to call one of the related functions.

The workaround as suggested by @sdragonx works. Of course I don't know if the criteria ("VK_EXT_swapchain_colorspace is supported, so VK_KHR_swapchain must be too") is the right one.

It's not an aliasing issue because the latter doesn't seem to add new functions. Though the spec (https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_swapchain_colorspace.html) seems incomplete as far as I can see.

**Comment by Dav1dde** [comment]
Ah yes you need to load multiple times to get access to all features, because some are instance or device specific, e.g. the example loads 3 times:

* https://github.com/Dav1dde/glad/blob/f237a2bfcec0d9b82b90ec9af4af265c40de7183/example/c/vulkan_tri_glfw/vulkan_tri_glfw.c#L1698
* https://github.com/Dav1dde/glad/blob/f237a2bfcec0d9b82b90ec9af4af265c40de7183/example/c/vulkan_tri_glfw/vulkan_tri_glfw.c#L1838
* https://github.com/Dav1dde/glad/blob/f237a2bfcec0d9b82b90ec9af4af265c40de7183/example/c/vulkan_tri_glfw/vulkan_tri_glfw.c#L1964
