### ISSUE TITLE
Compiler error C2099 when trying to compile GLAD2 Vulkan 1.3 in MSVC compiler

### ISSUE THREAD

**Issue by WSSDude420** [Dav1dde/glad#358]
![image](https://user-images.githubusercontent.com/41929176/153060042-12235c38-8897-4401-a98c-b46c9dbc0e37.png)

This issue is resolved with simple change in #357 . 
It is a simple C template change which changes `static const type value;` into `#define (type)value` in those cases it was emiting a warning.

**Comment by skaarj1989** [comment]
This problem also occurs with **VK_KHR_synchronization2** extension.
@Dav1dde Any chance to take a look at this?
I'd really like to continue to use glad2, but this is a major blocking point for me.

**Comment by Dav1dde** [comment]
Hey, sorry for ignoring this and being a bit MIA, was busy with other stuff and this looked pretty low priority to me (only a warning).

The problem with the MR is, this potentially changes the resulting binary, linkage etc and I don't wanna merge this without thinking it through first, but thanks for the MR helped me find the right spot. I wanna keep it open because this is the better solution for code readability.

I just pushed a commit to the glad2 branch that should fix this, can you please verify for that me?

**Comment by WSSDude420** [comment]
It fixed it 👍 
Closing this issue and my MR.
