### ISSUE TITLE
--merge doesn't merge loaders?

### ISSUE THREAD

**Issue by haasn** [Dav1dde/glad#372]
Hey,

I'm using GL in a way that's largely agnostic between GL core and GLES, so I'm naturally using the `--merge` option. One thing that surprised me is that, despite GL and GLES functions sharing the same function table now, `gladLoaderLoadGLContext` and `gladLoaderLoadGLES2Context` are still considered separate functions.

Right now, it seems I have to choose the right function to call based on inspecting `GL_VERSION` myself - which seems highly redundant with what glad is already doing.

Wouldn't it make much more sense for `--merge` to create a merged loader that loads the right API function set (GL or GLES2) depending on the `GL_VERSION` string automatically?

**Comment by Dav1dde** [comment]
Why do you inspect `GL_VERSION`? For GLES you have to request a a different context, so the idea is you call the initializer for the context you requested.

**Comment by haasn** [comment]
I am writing a library that gets implicitly passed a GL context (bound to the current thread) by the user, so I need to figure out which version of the context to load.

While I *could* require the user specify up-front whether it's a Desktop or ES context, this would be a rather annoying non-backwards compatible change because previous versions of the library (based on libepoxy instead of glad) did not require this.

**Comment by Dav1dde** [comment]
For glad GL and GLES are still separate APIs the `--merge` option only collapses the identically named symbols, but the whole loading machinery still loads separately. E.g. glad won't attempt to load a GL only function when instructed to load GLES, the same is true for symbols like `GLAD_GL_ES_VERSION_*` and `GLAD_GL_VERSION_*`.

So depending on what you load you get different symbols, which is properly represented in the API.

I currently don't think I want to introduce a "Auto Loader" function/facade which depending on the version returned calls the correct loader.

Depending on your usecase you can always call both loaders (Note: you wont be able to rely on `GLAD_*_VERSION_*` constants), or maybe the on-demand generation function is helpful (which is very close to libepoxy) and with on-demand you can set the same loader for both APIs.

Out of curiosity, how do you decide which loader to pass to glad, since this is also context dependent, or are you using GLFW/SDL which take care of this?

**Comment by haasn** [comment]
I think for the time being I will just call both loader functions, in the hopes of picking up every function in the end. The risk of a "false positive" (i.e. trying to load a GLES function on a GL) is pretty negligible in practice, anyway. (And actually, sort of required - because in practice, I need to load some GLES functions even on Desktop GL contexts - it's complicated)

> Out of curiosity, how do you decide which loader to pass to glad, since this is also context dependent, or are you using GLFW/SDL which take care of this?

If the API user provides a `GetProcAddress` callback, I can use that. If they do not, I would fall back to whatever the built-in loader does (dlopen-based afaict?).

**Comment by Dav1dde** [comment]
> The risk of a "false positive" (i.e. trying to load a GLES function on a GL) is pretty negligible in practice, anyway.

It shouldn't matter as long as you only call the right set of functions at runtime.

>  I would fall back to whatever the built-in loader does (dlopen-based afaict?).

`dlopen` to get the platform specific function to query the pointers, this can fail (e.g. on most Windows systems for GLES), but as long as one succeeds you're good to go.

**Comment by haasn** [comment]
> It shouldn't matter as long as you only call the right set of functions at runtime.

I suppose one remaining downside is that this implies unnecessarily calling `dlopen` / `dlclose` twice, when once would suffice with a merged loader.

**Comment by Dav1dde** [comment]
I assume this is answered/solved.
