### ISSUE TITLE
Support multiple profile in one application

### ISSUE THREAD

**Issue by hotgloupi** [Dav1dde/glad#41]
Hello,

My idea is to support both OpenGL 3.2 core profile and OpenGL 2.1 compat as a fallback, does that make any sense do that at runtime ?
Technically, I was about to hide all opengl calls in a wrapper, and including the glad.c file for each supported version (without exporting any symbols).
The other solution that came to mind was to export two loading functions, one for load 2.1-compat and one for 3.2-core. Then, I simply use the 3.2 core header file everywhere in the project (to avoid using the old API) for the GL_ defines, while still hiding the function calls using a wrapper.

How does one build a binary that can use two different versions of OpenGL ?

**Comment by Dav1dde** [comment]
Generate a 3.2 compatibility loader and use it for both contexts. In the 3.2 core context you will have functions which are not loaded, it's up to you to **not** call them. Same with the 2.1 context, all newer functions will not be loaded (correctly).

Generally only generating the versions which you will end up using makes it easier, because you won't end up calling unloaded functions by accident. But nothing speaks against generating glad with the superset of all versions you want to use and make sure you always only call the loaded functions.

**Comment by hotgloupi** [comment]
Thx ! I just noticed that gladLoadGLLoader() returns true whenever some version of OpenGL is found.
It's now up to me to ask for the right opengl context profile according to the GLAD_GL_VERSION_* values.
Thx for your input :)
