### ISSUE TITLE
Using GLX on Apple?

### ISSUE THREAD

**Issue by dmurdoch** [Dav1dde/glad#412]
I am trying to add glad to an existing project that was written a long time ago to use OpenGL 1.x.  I'd like access to OpenGL 2.1 functions to use shaders.

The project (https://github.com/dmurdoch/rgl) was originally written with three sets of fixed loaders, for Win32, AGL, and GLX.  I dropped the AGL code some years ago, and started using GLX on Apple (provided by XQuartz).

I'd like to use glad now to hopefully simplify things a bit, so I don't have to write a loader for the shader functions completely from scratch.

On a Mac, glad appears to be using native Apple OpenGL, so I'm making changes to the generated loader.  So far I have made these changes:

 - defined GLAD_PLATFORM_APPLE to always be 0, so we're working in GLX.
 - added the Apple lib locations to the list that glad_gl_dlopen_handle looks in.
 
With those changes, I see this:

  - it finds the OpenGL lib
  - it fails to find `glXGetProcAddressARB`
  - it finds `glGetString`
  - when it calls `glad_glGetString(GL_VERSION)`, it receives `NULL`, and quits.

Now I'm stumped.  Have I missed some necessary step?

**Comment by Dav1dde** [comment]
`glXGetProcAddressARB` must be statically exported from the OpenGL lib, if that's not there you can already abort. Check if the OpenGL lib actually does not export the symbol.

If it is exported and you got it to load, make sure you have an active OpenGL Context!

You might also be better off to implement your own loader and pass the loader to `gladLoadGL`, the internal loader is pure convenience but most of the time for a serious project it is not the correct choice. Since loading the functions depends on the GL context, you would want to use the loader function exposed by your windowing framework (e.g. `glfwGetProcAddress`) because only that knows what was used to setup the context.
If you roll your own windowing framework, this also applies.

**Comment by dmurdoch** [comment]
Thanks for your help.  I took a few wrong turns, but now things are working with your original code.  The crucial error was the simple one you mentioned in your second paragraph:  I didn't have an active OpenGL context.  I'll investigate using my own loader.
