### ISSUE TITLE
CMake glad_add_library(): REPRODUCIBLE keyword

### ISSUE THREAD

**Issue by M2-TE** [Dav1dde/glad#445]
I could not find any information regarding the **REPRODUCIBLE** keyword, which is used in some of the CMake examples for glad_add_library(). The option also doesn't seem to be listed in the main CMakeLists.txt under cmake/, so what exactly does this option do?

**Comment by Dav1dde** [comment]
Ah I never added it to the docs... 

Everytime you run glad it pulls the latest specifications from github and uses those to generate the loader, this means you need an active network connection and that between runs the output may change. It can also (very rarely) happen that upstream introduces a breaking change and your glad version doesn't support these specs anymore -> your build breaks.

The reproducible option uses packaged specifications instead, they are potentially a bit outdated but this means there are no more network requests and your build will never fail due to updated/changed upstream specifications.

 So generally I recommend you to use the reproducible option if you use cmake, this does not matter much if you generate manually and check in the generated code (which is what you should do imo).
