### ISSUE TITLE
Function that are undefined in c/c+, because defined c/c++ in debug version.

### ISSUE THREAD

**Issue by tndev** [Dav1dde/glad#55]
I currently noticed that if you download the c/c++ glad file for 4.5 core and use it in a system supports less then 4.5 then in the release build all function pointers that are not available with the version before 4.5 point to _nothing_, so you could write something like that:

    if( !glCopyNamedBufferSubData ) {
         // do some fallback if glCopyNamedBufferSubData does not exists
    }

But in the debug build all functions have the `_pre_call_callback`, `_post_call_callback`  wrapper, so all functions are set even if they are not support by the current platform.

Is the behaviour intended?

**Comment by Dav1dde** [comment]
Checking for null is not the right way to check if something is supported or not:

> https://www.opengl.org/registry/specs/ARB/get_proc_address.txt
> The pointer returned should be cast to a function pointer type matching
    the extension function's definition in that extension specification.
    A return value of NULL indicates that the specified function does
    not exist for the implementation.
>   A non-NULL return value for glXGetProcAddressARB **does not guarantee
    that an extension function is actually supported at runtime**. The
    client must must also query glGetString(GL_EXTENSIONS) or
    glXQueryExtensionsString to determine if an extension is supported
    by a particular context.

Glfw also documents this behavior:
> http://www.glfw.org/docs/latest/group__context.html#ga35f1837e6f666781842483937612f163
> The address of a given function is not guaranteed to be the same between contexts.
This function may return a non-NULL address despite the associated version or extension not being available. Always check the context version or extension string first.

This means your check is flawed since the beginning you should rather check for the version/extension explicitly instead. 
To answer the question, it is not intended, but also not a bug (the technical reason: it just makes everything a lot easier).
