### ISSUE TITLE
Option to add argument names to function macros in glad.h

### ISSUE THREAD

**Issue by garynull** [Dav1dde/glad#64]
I have made a quick modification to GLAD to generate argument names for the macros in `glad.h`, so I can use my IDE to see the GL function signature. Otherwise, I find myself having to look up the documentation for less common GL functions as I'm writing code.

For example, this:
```c
#define glTexImage2D glad_glTexImage2D
```

Is instead generated as:
```c
#define glTexImage2D(GLenum_target, GLint_level, GLint_internalformat, GLsizei_width, GLsizei_height, GLint_border, GLenum_format, GLenum_type, const_voidp_pixels) glad_glTexImage2D(GLenum_target, GLint_level, GLint_internalformat, GLsizei_width, GLsizei_height, GLint_border, GLenum_format, GLenum_type, const_voidp_pixels)
```

I'm willing to submit this feature as a pull request if anyone's interested (it works great for me). If so, should I base it on the **master** branch, or **glad2**? I'm new to GitHub so I'm not sure what kind of preferences the project author might have with regard to patches. Thanks!

**Comment by Dav1dde** [comment]
Hey, 

your IDE should be smart enough to resolve the Macros. I actually had your behaviour the default for Glad 2 for a bit until I realized that this unfortunately breaks code, you no longer can take the address of the function pointer.

```c
#include <iostream>
#include <string>


void test(int i) {
    std::cout << "Test -> " << i << "\n";    
}

#define foo test
#define bar(i) bar(i)

int main()
{
  (*(&test))(3);
  (*(&foo))(5);
  (*(&bar))(7); // < Error
}
```

And I think there were a few more problems with it .. I just can't think of them right now.

If that works for you it is great, I am just not sure if it makes sense to include it since it will break when you least need it.

So I am not sure if including such an option would make sense. If you still wanna make the Pull Request (can't promise anything), you should do it for the glad2 branch, since I am will not work on new features for glad1 (master). Note: the generator for glad2 is completely different and uses a proper template engine now, so the code you wrote for glad1 (master) won't be easily portable (but overall it should be way easier to include).

**Comment by garynull** [comment]
> your IDE should be smart enough to resolve the Macros.

I have updated my IDE to a new version since I last ran GLAD, so I checked, and it resolves the macros now!

Looks like it's all good. Thanks very much for taking the time.

(And if I make any other useful changes I will be sure to send pull requests using the glad2 branch.)
