### ISSUE TITLE
FR: Support runtime enable/disable of debugging

### ISSUE THREAD

**Issue by l0calh05t** [Dav1dde/glad#68]
Currently, we can explicitly disable debugging for individual functions by doing, e.g., `glad_debug_glClear = glad_glClear;`. It would be nice if glad defined a pair of functions such as `gladEnableDebugging` and `gladDisableDebugging` which do this for all functions (enable obviously resetting the function pointers to their original values with callback). That way we could enable/disable debugging on demand at runtime and not only at compile time.

**Comment by Dav1dde** [comment]
You can set the callbacks to empty functions to "disable" debugging and set them back if you want to enable it again. For a release build you shouldn't use a debug build anyways (if the two additional calls are too expensive for you).

**Comment by l0calh05t** [comment]
As stated in the OP, I already know how to disable/enable debugging for individual functions. However, doing that for all functions (the set of which varies depending on GLAD settings!) is not practical without generating the corresponding code.

**Comment by l0calh05t** [comment]
This also allows on-demand debugging without the overhead and without rebuilding

**Comment by Dav1dde** [comment]
Setting the callback function to a no-op basically disables the debugging, you still have the indirection (and 2 additional function calls), but that's not really relevant because you shouldn't be using the debug build of glad for a release anyways.

I just don't see enough value to generate these functions. I will keep it in the back of my head and maybe make it an option in the glad rework.

**Comment by Person27** [comment]
Any updates on this?

**Comment by Dav1dde** [comment]
3 Years later, this is implemented in glad2 now through the functions `gladInstall{API}Debug` and `gladUninstall{API}Debug`.
