### ISSUE TITLE
About code complete

### ISSUE THREAD

**Issue by tianyu-bai** [Dav1dde/glad#83]
Hi,
   Glad is a very good loading library for gl extensions, but when I use it, I find a code complete question. Because all the functions are defined to be macros in file "glad.h", so when I input the gl functions, my Xcode could not give me the functions' parameter snippets. So, is there some perfect solutions to solve this little inconvenience?

**Comment by Shimmen** [comment]
It really depends on how smart your IDE is. Xcode doesn't look beyond the macros (and I don't think Visual Studio does either), but when I use [CLion](https://www.jetbrains.com/clion/) it does.

As for a solution, if it is very important for you to have code completion for GL calls I would recommend CLion. If you don't want to change IDE or pay for it, I would instead recommend having [docs.gl](http://docs.gl) on an open browser tab and look there when you need it.

**Comment by Dav1dde** [comment]
This issue came also up in #11 and #64, there is a "fix" for it, glad could add arguments to the macros, but that just introduces more issues and doesn't add type information.

There is a workaround which sometimes works. 
With some include "magic" you can trick your IDE:

```c
#if _COMPILED // <- when read by the compiler
    #include <glad/glad.h>
#else // <- when read by your IDE
    // or a header file from e.g. here https://github.com/KhronosGroup/OpenGL-Registry
    #include <gl/gl.h>  
#endif
```

If you are able to change your IDE (as @Shimmen noted) you might want to look into another IDE which is more powerful (even though I don't think resolving macros should be considered an advanced feature).
