### ISSUE TITLE
GLAD already included #error is driving me nuts.

### ISSUE THREAD

**Issue by ButchDean** [Dav1dde/glad#84]
Hi,

I have been wrestling with GLAD on Linux now for a number of weeks but cannot seem to escape

> In file included from base/inc/core/shader_manager.h:4:0,
                 from base/src/main.cpp:17:
base/inc/glad/glad.h:577:2: error: #error OpenGL header already included, remove this include, glad already provides it
 #error OpenGL header already included, remove this include, glad already provides it

For [this specific branch](https://github.com/ButchDean/antivirus3-game-linux/tree/stripoldgraphics) of my project. I have only included glad in [mesh_generator.h](https://github.com/ButchDean/antivirus3-game-linux/blob/stripoldgraphics/base/inc/core/mesh_generator.h) and [shader_manager.h](https://github.com/ButchDean/antivirus3-game-linux/blob/stripoldgraphics/base/inc/core/shader_manager.h), so what am I doing wrong? I understand that this project is a little complicated, but would like to know what is going on.

Thank you.

**Comment by ButchDean** [comment]
BTW, I totally understand that it is stating that I have included the OpenGL header that GLAD provides, but this very specifically breaks code.

**Comment by Dav1dde** [comment]
The error means that the compiler finds a `gl.h` include before the `glad.h` include, which can be through any dependency, most likely GLFW.

A simple include graph:
![graph](https://cloud.githubusercontent.com/assets/255721/26033329/40582aee-38aa-11e7-8939-bf3506fa3e13.png)

Your `main.cpp` includes `core/game_superclass.h` which then includes `core/poll_keyboard.h` very early, which has a dependency on glfw, which then includes `gl.h`, later on you will include glad, but by this time `gl.h` was already included (Fuck yeah C!).

I defined `GLFW_INCLUDE_NONE` in your `main.cpp` (it makes glfw not include `g.h` publically), but then compilation fails because of missing types in `core/camera_data.h`.

Probably easiest fix is including glad at the very top of `core/game_superclass.h`, imo a better way of handling this include mess is creating a header file which includes gl for you and one which includes glfw for you, in the first you include second in the latter you either define the `GLFW_INCLUDE_NONE` or include your gl header before glfw. And whenever you need gl or glfw you include either of these headers.

**Comment by Dav1dde** [comment]
Ah I forgot:

```diff
diff --git a/Makefile b/Makefile
index 2f3ae96..178e42e 100755
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 #Libs to link against
-GRAPHICSLIBS = -lX11 -lXxf86vm -lXrandr -lXi -lGL -lGLU -lGLEW
+GRAPHICSLIBS = -lX11 -lXxf86vm -lXrandr -lXi -lGL -lGLU -ldl
 PTHREADLIBS = -lm -lpthread
 RMF = rm -f
 EXE = avgame
diff --git a/base/inc/core/game_superclass.h b/base/inc/core/game_superclass.h
index 298e79b..10fba05 100644
--- a/base/inc/core/game_superclass.h
+++ b/base/inc/core/game_superclass.h
@@ -1,6 +1,7 @@
 #ifndef _AVGAME_SUPER_
 #define _AVGAME_SUPER_
 
+#include <glad/glad.h>
 #include <core/poll_mouse.h>
 #include <core/poll_keyboard.h>
 #include <core/game_debug.h>
```

The diff which makes your project compile.

**Comment by ButchDean** [comment]
Thank you so much @Dav1dde ! This is great! The detailed explanation is also appreciated. :+1:
